[package]
name = "comfy-print"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Non-panicking versions of println! and friends"
repository = "https://github.com/Houtamelo/comfy-print"
readme = "README.md"
keywords = ["println", "debug", "write", "io", "stream"]
categories = ["os", "rust-patterns", "development-tools", "development-tools::debugging"]
exclude = ["comfy_print_tests/*"]

[dependencies]
parking_lot = "0.12.1"

[features]
default = []
async_impl = []
